config/routes.rb
OCv2::Application.routes.draw do
  get "home/index"

  devise_for :users, :class_name => "Customer::User", :controllers => { :omniauth_callbacks => "customer/omniauth_callbacks" }

  namespace :customer do resources :users end

  namespace :restaurant do resources :restaurants end

  namespace :restaurant do resources :dishes end

  get "management/index"

  devise_for :admins, :class_name => "Restaurant::Admin"

  match 'restaurant/panel' => 'restaurant/management#index'
  namespace :restaurant do resources :admins end

   root :to => 'home#index'

end

app/models/customer.rb
module Customer
  def self.table_name_prefix
    'customer_'
  end
end

app/models/customer/user.rb
class Customer::User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable , :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  def self.find_for_facebook_oauth(access_token, signed_in_resource=nil)
        data = access_token.extra.raw_info
        if customer_user == Customer::User.where(:email => data.email).first
          customer_user
        else # Create a user with a stub password.
          Customer::User.create!(:email => data.email, :password => Devise.friendly_token[0,20])
        end
      end
end

app/controllers/customer/omniauth_callbacks_controller.rb
class Customer::OmniauthCallbacksController < ApplicationController
  def facebook
      # You need to implement the method below in your model
      @customer_user = Customer::User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

      if @customer_user.persisted?
        flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
        sign_in_and_redirect @customer_user, :event => :authentication
      else
        session["devise.facebook_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
  end
  def self.find_for_facebook_oauth(access_token, signed_in_resource=nil)
      data = access_token.extra.raw_info
      if user = Customer::User.where(:email => data.email).first
        user
      else # Create a user with a stub password.
        Customer::User.create!(:email => data.email, :password => Devise.friendly_token[0,20])
      end
    end
end

app/controllers/customer/users_controller.rb
class Customer::UsersController < ApplicationController
  # GET /customer/users
  # GET /customer/users.json
  def index
    @customer_users = Customer::User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @customer_users }
    end
  end

  # GET /customer/users/1
  # GET /customer/users/1.json
  def show
    @customer_user = Customer::User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @customer_user }
    end
  end

  # GET /customer/users/new
  # GET /customer/users/new.json
  def new
    @customer_user = Customer::User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @customer_user }
    end
  end

  # GET /customer/users/1/edit
  def edit
    @customer_user = Customer::User.find(params[:id])
  end

  # POST /customer/users
  # POST /customer/users.json
  def create
    @customer_user = Customer::User.new(params[:customer_user])

    respond_to do |format|
      if @customer_user.save
        format.html { redirect_to @customer_user, notice: 'User was successfully created.' }
        format.json { render json: @customer_user, status: :created, location: @customer_user }
      else
        format.html { render action: "new" }
        format.json { render json: @customer_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /customer/users/1
  # PUT /customer/users/1.json
  def update
    @customer_user = Customer::User.find(params[:id])

    respond_to do |format|
      if @customer_user.update_attributes(params[:customer_user])
        format.html { redirect_to @customer_user, notice: 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @customer_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customer/users/1
  # DELETE /customer/users/1.json
  def destroy
    @customer_user = Customer::User.find(params[:id])
    @customer_user.destroy

    respond_to do |format|
      format.html { redirect_to customer_users_url }
      format.json { head :ok }
    end

  end

  def self.new_with_session(params, session)
      super.tap do |user|
        if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
          customer_user.email = data["email"]
        end
      end
    end

end

app/helpers/customer/users_helper.rb
module Customer::UsersHelper
end

app/views/customer/users/_form.html.erb
<%= form_for(@customer_user) do |f| %>
  <% if @customer_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer_user.errors.count, "error") %> prohibited this customer_user from being saved:</h2>

      <ul>
      <% @customer_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customer/users/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/customer/users/edit.html.erb
<h1>Editing customer_user</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer_user %> |
<%= link_to 'Back', customer_users_path %>

app/views/customer/users/index.html.erb
<h1>Listing customer_users</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @customer_users.each do |customer_user| %>
  <tr>
    <td><%= customer_user.name %></td>
    <td><%= link_to 'Show', customer_user %></td>
    <td><%= link_to 'Edit', edit_customer_user_path(customer_user) %></td>
    <td><%= link_to 'Destroy', customer_user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_customer_user_path %>

app/views/customer/users/new.html.erb
<h1>New customer_user</h1>

<%= render 'form' %>

<%= link_to 'Back', customer_users_path %>

app/views/customer/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @customer_user.name %>
</p>


<%= link_to 'Edit', edit_customer_user_path(@customer_user) %> |
<%= link_to 'Back', customer_users_path %>