config/routes.rb
OCv2::Application.routes.draw do
  get "home/index"

  devise_for :users, :class_name => "Customer::User", :controllers => { :omniauth_callbacks => "customer/omniauth_callbacks" }

  namespace :customer do resources :users end

  namespace :restaurant do resources :restaurants end

  namespace :restaurant do resources :dishes end

  get "management/index"

  devise_for :admins, :class_name => "Restaurant::Admin"

  match 'restaurant/panel' => 'restaurant/management#index'
  namespace :restaurant do resources :admins end

   root :to => 'home#index'

end

app/models/restaurant.rb
module Restaurant
  def self.table_name_prefix
    'restaurant_'
  end
end

app/models/restaurant/admin.rb
class Restaurant::Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

end

app/models/restaurant/dish.rb
class Restaurant::Dish < ActiveRecord::Base
end

app/models/restaurant/restaurant.rb
class Restaurant::Restaurant < ActiveRecord::Base
end

app/controllers/restaurant/admins_controller.rb
class Restaurant::AdminsController < ApplicationController
  # GET /restaurant/admins
  # GET /restaurant/admins.json
  def index
    @restaurant_admins = Restaurant::Admin.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @restaurant_admins }
    end
  end

  # GET /restaurant/admins/1
  # GET /restaurant/admins/1.json
  def show
    @restaurant_admin = Restaurant::Admin.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @restaurant_admin }
    end
  end

  # GET /restaurant/admins/new
  # GET /restaurant/admins/new.json
  def new
    @restaurant_admin = Restaurant::Admin.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @restaurant_admin }
    end
  end

  # GET /restaurant/admins/1/edit
  def edit
    @restaurant_admin = Restaurant::Admin.find(params[:id])
  end

  # POST /restaurant/admins
  # POST /restaurant/admins.json
  def create
    @restaurant_admin = Restaurant::Admin.new(params[:restaurant_admin])

    respond_to do |format|
      if @restaurant_admin.save
        format.html { redirect_to @restaurant_admin, notice: 'Admin was successfully created.' }
        format.json { render json: @restaurant_admin, status: :created, location: @restaurant_admin }
      else
        format.html { render action: "new" }
        format.json { render json: @restaurant_admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /restaurant/admins/1
  # PUT /restaurant/admins/1.json
  def update
    @restaurant_admin = Restaurant::Admin.find(params[:id])

    respond_to do |format|
      if @restaurant_admin.update_attributes(params[:restaurant_admin])
        format.html { redirect_to @restaurant_admin, notice: 'Admin was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @restaurant_admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurant/admins/1
  # DELETE /restaurant/admins/1.json
  def destroy
    @restaurant_admin = Restaurant::Admin.find(params[:id])
    @restaurant_admin.destroy

    respond_to do |format|
      format.html { redirect_to restaurant_admins_url }
      format.json { head :ok }
    end
  end
end

app/controllers/restaurant/dishes_controller.rb
class Restaurant::DishesController < ApplicationController
  # GET /restaurant/dishes
  # GET /restaurant/dishes.json
  def index
    @restaurant_dishes = Restaurant::Dish.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @restaurant_dishes }
    end
  end

  # GET /restaurant/dishes/1
  # GET /restaurant/dishes/1.json
  def show
    @restaurant_dish = Restaurant::Dish.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @restaurant_dish }
    end
  end

  # GET /restaurant/dishes/new
  # GET /restaurant/dishes/new.json
  def new
    @restaurant_dish = Restaurant::Dish.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @restaurant_dish }
    end
  end

  # GET /restaurant/dishes/1/edit
  def edit
    @restaurant_dish = Restaurant::Dish.find(params[:id])
  end

  # POST /restaurant/dishes
  # POST /restaurant/dishes.json
  def create
    @restaurant_dish = Restaurant::Dish.new(params[:restaurant_dish])

    respond_to do |format|
      if @restaurant_dish.save
        format.html { redirect_to @restaurant_dish, notice: 'Dish was successfully created.' }
        format.json { render json: @restaurant_dish, status: :created, location: @restaurant_dish }
      else
        format.html { render action: "new" }
        format.json { render json: @restaurant_dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /restaurant/dishes/1
  # PUT /restaurant/dishes/1.json
  def update
    @restaurant_dish = Restaurant::Dish.find(params[:id])

    respond_to do |format|
      if @restaurant_dish.update_attributes(params[:restaurant_dish])
        format.html { redirect_to @restaurant_dish, notice: 'Dish was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @restaurant_dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurant/dishes/1
  # DELETE /restaurant/dishes/1.json
  def destroy
    @restaurant_dish = Restaurant::Dish.find(params[:id])
    @restaurant_dish.destroy

    respond_to do |format|
      format.html { redirect_to restaurant_dishes_url }
      format.json { head :ok }
    end
  end
end

app/controllers/restaurant/management_controller.rb
class Restaurant::ManagementController < ApplicationController
  before_filter :authenticate_admin!
  def index
  end

end

app/controllers/restaurant/restaurants_controller.rb
class Restaurant::RestaurantsController < ApplicationController
  # GET /restaurant/restaurants
  # GET /restaurant/restaurants.json
  def index
    @restaurant_restaurants = Restaurant::Restaurant.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @restaurant_restaurants }
    end
  end

  # GET /restaurant/restaurants/1
  # GET /restaurant/restaurants/1.json
  def show
    @restaurant_restaurant = Restaurant::Restaurant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @restaurant_restaurant }
    end
  end

  # GET /restaurant/restaurants/new
  # GET /restaurant/restaurants/new.json
  def new
    @restaurant_restaurant = Restaurant::Restaurant.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @restaurant_restaurant }
    end
  end

  # GET /restaurant/restaurants/1/edit
  def edit
    @restaurant_restaurant = Restaurant::Restaurant.find(params[:id])
  end

  # POST /restaurant/restaurants
  # POST /restaurant/restaurants.json
  def create
    @restaurant_restaurant = Restaurant::Restaurant.new(params[:restaurant_restaurant])

    respond_to do |format|
      if @restaurant_restaurant.save
        format.html { redirect_to @restaurant_restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render json: @restaurant_restaurant, status: :created, location: @restaurant_restaurant }
      else
        format.html { render action: "new" }
        format.json { render json: @restaurant_restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /restaurant/restaurants/1
  # PUT /restaurant/restaurants/1.json
  def update
    @restaurant_restaurant = Restaurant::Restaurant.find(params[:id])

    respond_to do |format|
      if @restaurant_restaurant.update_attributes(params[:restaurant_restaurant])
        format.html { redirect_to @restaurant_restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @restaurant_restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurant/restaurants/1
  # DELETE /restaurant/restaurants/1.json
  def destroy
    @restaurant_restaurant = Restaurant::Restaurant.find(params[:id])
    @restaurant_restaurant.destroy

    respond_to do |format|
      format.html { redirect_to restaurant_restaurants_url }
      format.json { head :ok }
    end
  end
end

app/helpers/restaurant/admins_helper.rb
module Restaurant::AdminsHelper
end

app/helpers/restaurant/dishes_helper.rb
module Restaurant::DishesHelper
end

app/helpers/restaurant/management_helper.rb
module Restaurant::ManagementHelper
end

app/helpers/restaurant/restaurants_helper.rb
module Restaurant::RestaurantsHelper
end

app/views/restaurant/restaurants/_form.html.erb
<%= form_for(@restaurant_restaurant) do |f| %>
  <% if @restaurant_restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant_restaurant.errors.count, "error") %> prohibited this restaurant_restaurant from being saved:</h2>

      <ul>
      <% @restaurant_restaurant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :contact_info %><br />
    <%= f.text_area :contact_info %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurant/restaurants/edit.html.erb
<h1>Editing restaurant_restaurant</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurant_restaurant %> |
<%= link_to 'Back', restaurant_restaurants_path %>

app/views/restaurant/restaurants/index.html.erb
<h1>Listing restaurant_restaurants</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Address</th>
    <th>Contact info</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @restaurant_restaurants.each do |restaurant_restaurant| %>
  <tr>
    <td><%= restaurant_restaurant.name %></td>
    <td><%= restaurant_restaurant.description %></td>
    <td><%= restaurant_restaurant.address %></td>
    <td><%= restaurant_restaurant.contact_info %></td>
    <td><%= link_to 'Show', restaurant_restaurant %></td>
    <td><%= link_to 'Edit', edit_restaurant_restaurant_path(restaurant_restaurant) %></td>
    <td><%= link_to 'Destroy', restaurant_restaurant, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Restaurant', new_restaurant_restaurant_path %>

app/views/restaurant/restaurants/new.html.erb
<h1>New restaurant_restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurant_restaurants_path %>

app/views/restaurant/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @restaurant_restaurant.name %>
</p>

<p>
  <b>Description:</b>
  <%= @restaurant_restaurant.description %>
</p>

<p>
  <b>Address:</b>
  <%= @restaurant_restaurant.address %>
</p>

<p>
  <b>Contact info:</b>
  <%= @restaurant_restaurant.contact_info %>
</p>


<%= link_to 'Edit', edit_restaurant_restaurant_path(@restaurant_restaurant) %> |
<%= link_to 'Back', restaurant_restaurants_path %>